name: User Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT

      - name: Checkout Repository
        uses: actions/checkout@v4

      # START TIMER

      - name: Start Timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      # CREATE LOG FILE

      - name: Create Log File
        run: touch pipeline.log

      # SETUP NODE

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # INSTALL

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..." | tee -a pipeline.log
          npm install 2>&1 | tee -a pipeline.log

      # TESTS

      - name: Run Tests
        run: |
          echo "Running tests..." | tee -a pipeline.log
          npm test 2>&1 | tee -a pipeline.log

      # BUILD IMAGE

      - name: Build Docker Image
        run: |
          echo "Building Docker image..." | tee -a pipeline.log
          docker build -t user-service . 2>&1 | tee -a pipeline.log

      # PUSH COMPLETE LOGS TO GRAFANA CLOUD LOKI

      - name: Push Logs to Grafana Loki
        if: always()

        env:
          LOKI_URL: ${{ secrets.GRAFANA_LOKI_URL }}
          LOKI_USERNAME: ${{ secrets.GRAFANA_USERNAME }}
          LOKI_API_KEY: ${{ secrets.GRAFANA_API_KEY }}

        run: |
          LOG_CONTENT=$(cat pipeline.log | sed 's/"/\\"/g')

          cat <<EOF > loki-payload.json
          {
            "streams": [
              {
                "stream": {
                  "service": "user-service",
                  "pipeline": "github-actions",
                  "repository": "${{ github.repository }}"
                },
                "values": [
                  [
                    "$(date +%s%N)",
                    "$LOG_CONTENT"
                  ]
                ]
              }
            ]
          }
          EOF

          curl -u "$LOKI_USERNAME:$LOKI_API_KEY" \
            -H "Content-Type: application/json" \
            -X POST \
            "$LOKI_URL" \
            --data-binary @loki-payload.json
